spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatroom
    username: root
    password: Wang
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.noregret.pojo

logging:
  level:
    root: off